wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/Degusta.png tinyurl.com/bdehz9bb

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Teatro con Sabores'.png tinyurl.com/58fnr5j7

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Tour por Colonia del Sacramento'.png tinyurl.com/3rp2vvjf

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Almuerzo en el Real de San Carlos'.png tinyurl.com/2yeu66vb

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Almuerzo en Valle del Lunarejo'.png tinyurl.com/4yrs8y2c

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Cabalgata en Valle del Lunarejo'.png tinyurl.com/2vjd382t

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Bus turístico Colonia'.png tinyurl.com/bdzyrm93

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Colonia PremiumTour'.png tinyurl.com/284kr973

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Deportes náuticos sin uso de motor'.png tinyurl.com/yck2a92h

wget -O eclipse-workspace/servidor-central/src/main/resources/images/Activity/'Descubre Rivera'.png tinyurl.com/y4vbc4xc


