wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/lachiqui.png tinyurl.com/2e3s66tw

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/isabelita.png https://media.revistavanityfair.es/photos/62de8ec79617e3f94e9f9f6f/master/w_1600%2Cc_limit/Isabel%2520II.png

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/anibal.png tinyurl.com/y2u3tybh

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/waston.png tinyurl.com/2p9ed8et

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/elelvis.png tinyurl.com/mtwppxxz

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/eleven11.png tinyurl.com/3ztpasya

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/bobesponja.png tinyurl.com/43zymcch

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/tony.png tinyurl.com/mr3a38w4

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/chino.png tinyurl.com/2b556k7t

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/mastropiero.png tinyurl.com/3mbeyawm

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/washington.png tinyurl.com/3whe8372

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/eldiez.png tinyurl.com/mu4jeas3

wget -O eclipse-workspace/servidor-central/src/main/resources/images/User/meche.png tinyurl.com/4hs4v9c5

